# Change these first
owner: BamseMoms # Your GitHub username
repo: Status # Your GitHub repository name

# Add your sites here
sites:
  - name: BamseMoms
    url: https://BamseMoms.mcgo.io

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: Status
  # Uncomment the following line if you don't have a custom domain and add your repo name
   baseUrl: /Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "1111"
  introMessage: "22222"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
